import { useState, useCallback } from 'react';
import { useAuth } from '../../../contex/authContext.jsx';
import { useTasks } from '../../hooks/useTasks';
import Sidebar from '../../components/Sidebar'; import NoteList from '../../components/NoteList'; import NoteEditor from '../../components/NoteEditor'; import SearchBar from '../../components/SearchBar'; import ConfirmDialog from '../../components/ConfirmDialog'; import '../../App.css';
export default function Dashboard() {
  const { logout } = useAuth(); const { tasks, loading, error, operation, filter, setFilter, selectedId, setSelectedId, selectedTask, addTask, editTask, removeTask, toggleComplete } = useTasks();
  const [search, setSearch] = useState(''); const [mobileSidebarOpen, setMobileSidebarOpen] = useState(false); const [mobileEditorOpen, setMobileEditorOpen] = useState(false); const [confirmDelete, setConfirmDelete] = useState(null);
  const filteredTasks = tasks.filter((t) => !search.trim() || t.title?.toLowerCase().includes(search.toLowerCase()) || t.description?.toLowerCase().includes(search.toLowerCase()));
  const select = useCallback((id) => { setSelectedId(id); setMobileEditorOpen(true); }, [setSelectedId]);
  const newNote = async () => { try { const task = await addTask({ title: 'New Note', description: '', isCompleted: false }); setSelectedId(task._id); setMobileEditorOpen(true); } catch { /* hook displays error */ } };
  const confirmDeleteAction = async () => { if (!confirmDelete) return; try { await removeTask(confirmDelete._id); setConfirmDelete(null); setMobileEditorOpen(false); } catch { /* keep dialog open */ } };
  const empty = error ? 'error' : search && !filteredTasks.length ? 'search' : !loading && !tasks.length ? 'empty' : null;
  return <div className="app"><Sidebar filter={filter} onFilterChange={setFilter} taskCount={tasks.length} mobileOpen={mobileSidebarOpen} onClose={() => setMobileSidebarOpen(false)} onLogout={logout} /><main className={`note-panel ${mobileEditorOpen && selectedTask ? 'note-panel--editor-open' : ''}`}><div className="note-panel__list"><div className="note-panel__topbar"><button className="note-panel__menu" onClick={() => setMobileSidebarOpen(true)} aria-label="Open sidebar">☰</button><h1 className="note-panel__heading">{filter === 'all' ? 'All Notes' : filter === 'active' ? 'Active' : 'Completed'}</h1><button className="note-panel__add" onClick={newNote} disabled={Boolean(operation)} aria-label="New note">＋</button></div><div className="note-panel__search"><SearchBar value={search} onChange={setSearch} /></div>{!loading && !error && tasks.length > 0 && <div className="note-panel__count">{filteredTasks.length} {filteredTasks.length === 1 ? 'note' : 'notes'}</div>}{loading ? <div className="note-panel__loading"><div className="spinner" /></div> : <NoteList tasks={filteredTasks} selectedId={selectedId} onSelect={select} emptyType={empty} />}</div><div className="note-panel__editor"><NoteEditor key={selectedTask?._id || '__none__'} task={selectedTask} onSave={editTask} onBack={() => { setMobileEditorOpen(false); setSelectedId(null); }} onDelete={(id) => setConfirmDelete(tasks.find((t) => t._id === id) || { _id: id })} onToggleComplete={toggleComplete} busy={Boolean(operation)} /></div></main>{confirmDelete && <ConfirmDialog title="Delete Note" message={`Are you sure you want to delete "${confirmDelete.title || 'this note'}"? This cannot be undone.`} onConfirm={confirmDeleteAction} onCancel={() => setConfirmDelete(null)} />}</div>;
}
